/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SaisieRouteImport } from './routes/saisie'
import { Route as PilotageRouteImport } from './routes/pilotage'
import { Route as IndexRouteImport } from './routes/index'

const SaisieRoute = SaisieRouteImport.update({
  id: '/saisie',
  path: '/saisie',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotageRoute = PilotageRouteImport.update({
  id: '/pilotage',
  path: '/pilotage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pilotage': typeof PilotageRoute
  '/saisie': typeof SaisieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pilotage': typeof PilotageRoute
  '/saisie': typeof SaisieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pilotage': typeof PilotageRoute
  '/saisie': typeof SaisieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pilotage' | '/saisie'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pilotage' | '/saisie'
  id: '__root__' | '/' | '/pilotage' | '/saisie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PilotageRoute: typeof PilotageRoute
  SaisieRoute: typeof SaisieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saisie': {
      id: '/saisie'
      path: '/saisie'
      fullPath: '/saisie'
      preLoaderRoute: typeof SaisieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilotage': {
      id: '/pilotage'
      path: '/pilotage'
      fullPath: '/pilotage'
      preLoaderRoute: typeof PilotageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PilotageRoute: PilotageRoute,
  SaisieRoute: SaisieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
