/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PilotageRouteImport } from './routes/pilotage'
import { Route as IndexRouteImport } from './routes/index'

const PilotageRoute = PilotageRouteImport.update({
  id: '/pilotage',
  path: '/pilotage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pilotage': typeof PilotageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pilotage': typeof PilotageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pilotage': typeof PilotageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pilotage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pilotage'
  id: '__root__' | '/' | '/pilotage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PilotageRoute: typeof PilotageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pilotage': {
      id: '/pilotage'
      path: '/pilotage'
      fullPath: '/pilotage'
      preLoaderRoute: typeof PilotageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PilotageRoute: PilotageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
